### ISSUE TITLE
Escaping of client-side template text nodes: configurable?

### ISSUE THREAD

**Issue by voborl00** [OWASP/java-html-sanitizer#124]
FilterUrlByProtocolAttributePolicy since this commit

https://github.com/OWASP/java-html-sanitizer/commit/4f9a7af04a906d03ce75561f513cf7b151025193#diff-19b1293d8d9bfd504bf66e0ab90d2415

forces normalizing of possible client-side template code (ie {} <% %> ...).

As StandardUrlAttributePolicy uses this normalizeUri() method as well, could there be some way (true/false or definition of allowed constructs) how to configure this behavior?

**Comment by mikesamuel** [comment]
Why would you want to configure this?

**Comment by voborl00** [comment]
Because I use sanitizer for non-pure html templates, which also contains some coding constructs/variables (even inside, for example, "href" attribute like <a href="{userTwitterLink}">My Twitter</a>). And as they start and end with curly brackets they are escaped through the sanitizing process which I want to disable. 

Versions up to this commit did not make this escaping and I hoped that behaviour change this big between  two sanitizer versions should be made configurable for at least backwards compatibility (I am now stuck with r239 release).

Thanks for understanding my case.

**Comment by mikesamuel** [comment]
The HTML sanitizer takes in HTML and outputs HTML.  I make no guarantees that it will work for HTML-like languages.

I also make no guarantees of backwards compatibility besides that contract since I need the flexibility to respond to emerging threats.  That requires changing details of the HTML produced.

I also have a very high bar for adding flags and options since every boolean option doubles the number of configurations I need to test to check that security properties hold.

**Comment by jmanico** [comment]
+1 Mike

To the question asker: Can you sanitize AFTER the template has rendered HTML per chance?

Aloha,
—
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by voborl00** [comment]
I think not (not without major code changes) as my use case is this:

- user creates HTML template (with these `{placeholders}` in href attributes) using WYSIWYG (CK Editor)
- this template is saved (and beforehand sanitized) so now I have "safe" HTML template with unescaped `href {placeholders}` repeatedly editable in editor
- independently some time after, background worker gets this template, makes all `{placeholder}` replacements (ie `href="{userTwitterLink}"` -> `href="https://www.twitter.com/myTwitter"`) and sends it away

With this client-side template escaping in new sanitizer versions I will end (after template is saved from CK Editor) with showing user in WYSIWYG templates like

`<a href="%7buserTwitterLink%7d">My Twitter</a>`

and there will be no match for `{placeholders}` in background worker as well.

Way out of this for me is replace back all `%7b` and `%7d` in all "uri attributes" after template is saved and sanitized (or hacking out those two switch cases for { and } directly in the sanitizer lib ;-)) which I wanted to disable in sanitizer at first place by posting this issue.

**Comment by jmanico** [comment]
As Mike said, sadly this is not the right library for you. The lib only guarantees HTML validation - not template validation. I hope Mike’s explanation is clear and I’m sorry that the change - which was done for stronger security - effected your work.

Aloha,
-
Jim Manico
@Manicode

**Comment by mikesamuel** [comment]
I think the following algo might work for you since I'm unlikely to muck with alphanumerics.

1.  Pick a random string of alphanumerics, `nonce`, until you find one that is not a substring of the input.
2.  Create a `List<String> storedTemplateExpressions`
3.  For each `{...}` expression in your input template where `i` is the `i-th` such expression,
  a. add it to `storedTemplateExpressions`
  b. replace it in the text with `'_" + nonce + "_" + i + "_"
4. Let `safeTemplate` be the result of sanitizing your template after replacing template expressions
5. Reverse step 3 on `safeTemplate` by replacing `Pattern.compile("_" + Pattern.quote(nonce) + "_(\\d+)_")` with `storedTemplateExpression.get(Integer.valueOf(matcher.group(1)))`.
