### ISSUE TITLE
library is not compatible with Guava 21.0 and later

### ISSUE THREAD

**Issue by ispringer** [OWASP/java-html-sanitizer#154]
I'd like to upgrade to the latest OWASP sanitizer. Unfortunately, I can't because it depends on a relatively old version of Guava (19.0), and specifically depends on Guava API's that no longer exist in Guava 21 and later. For example:

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/ips/Code/java-html-sanitizer/src/main/java/org/owasp/html/examples/EbayPolicyExample.java:[236,36] <anonymous org.owasp.html.examples.EbayPolicyExample$3> is not abstract and does not override abstract method test(java.lang.String) in java.util.function.Predicate
```

Is there any chance you can either upgrade to Guava 21.0, shade your Guava dependency, or drop your Guava dependency?

**Comment by mikesamuel** [comment]
What version of javac are you compiling with?  I wonder whether this might be a failure to recognize that java.util.function.Predicate::test is implemented via a default method in Guava 21's version of Predicate.

**Comment by ispringer** [comment]
I'm compiling with JDK8 (Guava 21 requires Java 8).

**Comment by mikesamuel** [comment]
Ok.  That's what I typically compile with.

I've ran into problems when I tried dropping the Guava dependency and have had frequent complaints about the open-endedness of the dependency: https://github.com/OWASP/java-html-sanitizer/issues?utf8=%E2%9C%93&q=is%3Aissue+guava+

I'm not super-familiar with Maven version resolution.  What would shading accomplish?  If that's related to having multiple versions of Guava via renaming, I'd rather not.  That sounds like a recipe for bugs and memory bloat since the use of Guava is not restricted to internal implementation details.

Upgrading to Guava 21 is not going to happen quickly -- I do not have a sense of the size of the Java7 installed base, and got Java6 compatibility issues reported long after I expected that to be long gone.

I might be able to provide an artifact for Guava19 and another one for Guava 21.

**Comment by mikesamuel** [comment]
@Rapster 

How did you conclude that it isn't used?

https://github.com/OWASP/java-html-sanitizer/blob/241b4b8a6cd37c486b36f12fc135a018881c3e4a/src/main/java/org/owasp/html/AttributePolicy.java#L31-L32

**Comment by Rapster** [comment]
Arf my bad, I expect guava would be part of the package... Since I didn't find any result with `guava` I concluded it was not used... Again sorry

**Comment by mikesamuel** [comment]
Ok.  I patched in 

```diff
diff --git a/parent/pom.xml b/parent/pom.xml
index cd25d9b..aa069a4 100644
--- a/parent/pom.xml
+++ b/parent/pom.xml
@@ -90,6 +90,7 @@ application while protecting against XSS.
   <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
+    <guava.version>19.0</guava.version>
   </properties>

   <build>
@@ -195,7 +196,7 @@ application while protecting against XSS.
       <dependency>
         <groupId>com.google.guava</groupId>
         <artifactId>guava</artifactId>
-        <version>19.0</version>
+        <version>${guava.version}</version>
       </dependency>
       <dependency>
         <groupId>commons-codec</groupId>
```

and then ran

```bash
$ mvn -f aggregate/pom.xml clean source:jar javadoc:jar verify
...
BUILD SUCCESS
...
$ mvn -Dguava.version=27.0-jre -f aggregate/pom.xml clean source:jar javadoc:jar verify
...
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project owasp-java-html-sanitizer: Compilation failure
[ERROR] /Users/msamuel/work/owasp-java-html-sanitizer/src/main/java/org/owasp/html/examples/EbayPolicyExample.java:[236,36] <anonymous org.owasp.html.examples.EbayPolicyExample$3> is not abstract and does not override abstract method test(java.lang.String) in java.util.function.Predicate
...
```

so that gives me something to grind away on and something I can put in `.travis.yml` to keep compatible with multiple Guava versions going forward.
