### ISSUE TITLE
"&nbsp;" returns space after sanitize instead of returning same "&nbsp;"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OWASP/java-html-sanitizer#30]
```
I can not say this is bug but may be the policy we configure is wrong.


On the string if have html entites "&nbsp;" than after sanitize it show (empty 
space) but not return "&nbsp;"  while for other example "&lt", "&gt" shows 
correctly after sanitize.

example,

final String test = "&nbsp;&gt;";

final PolicyFactory policy = Sanitizers.FORMATTING.and(
Sanitizers.BLOCKS).and(Sanitizers.STYLES);
final String safeHTML = policy.sanitize(test);

System.out.println("Before:" +test);
System.out.println("After:" +safeHTML);

Result:
-------
Before:&nbsp;&gt;
After: &gt;

Actually we need &nbsp; after sanitize so can your provide guidance on this how 
to achieve.

Thx in advance!

Kr,
Urvish
```

Original issue reported on code.google.com by `urvishmp...@gmail.com` on 23 May 2014 at 1:17

**Comment by urvishmparikh** [comment]
We have an another issue example, if you enter &#8217; sanitizer covert this to html character (´) which is not recognized by rendered engine (UTF-8).

Actually we are not understanding why santizer required to change html entities to characters. This happend to only some entites not for all (example &lt; is not converted)

Kr,
Urvish

**Comment by urvishmparikh** [comment]
Hi,

In fact if use different encoding rather than UTF-8 there is problem.
If use ISO-8859-1 it does not convert HTMLentities well to character.
But we are not understanding why it is required to convert HTML entities to character.
Example (default file encoding ISO-8599-1),
Before sanitize:
<p>browser&#8217;s</p>
After sanitize:
 <p>browser’s</p>
During rendering it is not recognize well it gives result:
browser?s

Kr,
U

**Comment by mikesamuel** [comment]
I'm not going to expand the space of configurations to specify different policies on entity encoding.

Expanding the configuration space reduces the mean test coverage per configuration and the minimum test coverage per configuration.

Noone has yet outlined a use-case that requires this extra configuration.

I have too many other demands on time to write and maintain lots of extra tests for configurations that don't meet a required use-case.

I can't recommend this library for use in production if the minimum test coverage per configuration is low.

I want to be able to recommend this library for use in production.

CJK languages compress better when arbitrary code-points are not encoded as character reference.

Therefore, until I see a clear and well-argued use-case,
I will not complicate the code that decides whether to encode a code-point as a character reference.

**Comment by tibistibi** [comment]
i can understand that you do not have time but that should not be an argument to close this issue. you can give it a low priority maybe some one else can take one.

you need a clear and well argued use case. ok here is mine.

i have a front-end where via a rich text editor a user can add content. which will be stored in the db and shown to users on some other page.
i want to make this secure so the editor can't add tags which are not allowed but he should still be able to add all the text he wants.
i also want to give clear error messages. 

so ideally i would receive the added text. i would run it through the sanitizer to remove tags i don't want. then i would compare the added text with the cleaned text. if this is different  i return an error telling the editor added wrong input.
second spaces should still be kept as &nbsp because multiple &nbsp is different presented in html than multiple spaces.

both scenario's are not possible because the text is encoded when i sanitize. encoding and sanitation are 2 different steps which should be two different steps in the code. this will not add you more unit tests it just would make the lib more modular. 

i won't mind helping out :smile:

**Comment by tibistibi** [comment]
from #43 to put all the examples in 1 issue
test case:

        @Test
        public void testSpace() {
            String text = "L&amp;nbsp;&amp;nbsp;&amp;nbsp;L";
            assertEquals(text, Sanitizers.FORMATTING.sanitize(text));
         }

why:
1)
a &amp;nbsp; is something different than a space. when i get a &amp;nbsp; from my richttext editor i want to preserve it. in the above example when i would add the sanitized text into an html page it would look like L L instead of L&nbsp;&nbsp;&nbsp;L.
2)
i want to know if the user added something wrong and present an error:

		if (!StringUtils.equals(text, clean)) {
			addFieldError("wrong input! please check cleaned text");
		}

i don't want this to happen after a spcae replacement.

todo:
remove the &amp;nbsp; to space part or make it optional.


work around: 
replace the &amp;nbsp; by spaces. do the sanitizing and checking and re add the &amp;nbsp;

**Comment by mikesamuel** [comment]
> i can understand that you do not have time but that should not be an argument to close this issue. you can give it a low priority maybe some one else can take this one.

It's not just that I don't have a lot of time, but also that I've seen nothing that leads me to believe that it serves a purpose ; I don't just prioritize it low, I can't distinguish its priority from Priority:Worthless.

**Comment by mikesamuel** [comment]
> `&nbsp;` is something different than a space

Agreed.  That's why I don't normalize it as [space (U+20)](http://www.fileformat.info/info/unicode/char/20/index.htm) and instead re-encode it as [non-breaking space (U+A0)](http://www.fileformat.info/info/unicode/char/A0/index.htm).

**Comment by tibistibi** [comment]
ok but for me this tool is worthless now because i need to sanitize and not decode/encode.

somehow it is not important for you to preserve added text. who can i sanitize and keep the text equal. how can i tell my users that they added wrong tags?

**Comment by mikesamuel** [comment]
Testing string equality is extremely brittle -- there are many HTML strings with the same semantics.

What does [`HtmlChangeListener`](https://rawgit.com/OWASP/java-html-sanitizer/master/distrib/javadoc/org/owasp/html/HtmlChangeListener.html) not provide that you need to do your check?

**Comment by tibistibi** [comment]
yes i was looking into that one interesting that i get an call for every change well every sanitize change. the decode encode changes are not send to a listener. 
but its not a problem that html strings have the same semantics when it stays the same i do not have to report any thing to the user.
but i agree with the listener i think i can report back to the user. 

so how can i keep the text equal?

**Comment by tibistibi** [comment]
i ran the test again with some extra chars and they all get changed.:

	@Test
	public void testSpace() {
		String text = "&nbsp;&nbsp;&nbsp; ' =  _+ ;'\" ";
		String result = Sanitizers.FORMATTING.sanitize(text);
		assertEquals(text, result);
	}

so the nbsp's get decoded and the others get encoded. what i find hard to understand is that you seem a very smart coder but don't mind a method does not do what it is called. when you create a method sanitize and what it does is sanitize and encode/decode i find it really confusing. apart that i cant' use the tool now. i either need to fork this or need to get the text out first and read it later.

**Comment by mikesamuel** [comment]
If you have problems with HtmlChangeListener, open an issue about that.

I define "sanitize" in a specific way that allows semantics preserving changes to documents in addition to elision.

If you choose to fork or not use the tool then good luck to you.

**Comment by tibistibi** [comment]
i don't have any problem with the HtmlCHangeListeren.

i think we agree on all but what you find semantics preserving changes for me (and the others above) are real changes which are not acceptable for me nor for my client. i will go on and fork it than

**Comment by mikesamuel** [comment]
> i think we agree on all but what you find semantics preserving changes for me

This is defined by the HTML5 specification.  It's not *just* a matter of opinion.

> i think your tool would be much better when you split the method sanitize into sanitize which will clean the text and a method dencode which will change chars for some reason.

This is not just a whim.  Sanitizing requires taking a large and inconsistently interpreted set of strings and producing an output that is in a safe and consistently interpreted set.  You seem to think that defining that subset without encoding/decoding is easy.  My experience writing sanitizers has taught me otherwise.

**Comment by mikesamuel** [comment]
If you're going to do string comparison, instead of doing

```java
String inputString = ...;
String sanitizedString = HTMLSanitizer.sanitize(inputString, myPolicy);
if (inputString.equals(sanitizedString)) {
  // Assume no tags or attributes rejected
} else {
  // Assume some tags or attributes rejected
}
```

why not do

```java
String inputString = ...;
String normalizedString = HTMLSanitizer.sanitize(inputString, policyThatAllowsEverything);
String sanitizedString = HTMLSanitizer.sanitize(inputString, myPolicy);
if (inputString.equals(sanitizedString)) {
  // Assume no tags or attributes rejected
} else {
  // Assume some tags or attributes rejected
}
```
?

That should make your equality test independent of any changes in the way text nodes are represented.

**Comment by tibistibi** [comment]
just  for future references I ran into another issue. with encoding text which is that we use place holders which get replaced by a process later in the chain. these text can be anything.
so if the place holder text would be te'st than it will be encoded to te&amp;#39;st and lose its place holder capability. 

one more thin when reading through the documentation i could not find anything about encoding. can you point me to these documents?

**Comment by mikesamuel** [comment]
Encoding and decoding of HTML text nodes are specified in http://www.w3.org/html/wg/drafts/html/master/single-page.html#character-references

**Comment by tibistibi** [comment]
thanks. but w3 does not say what this html sanitizer does.
i would expect somewhere a remark or documentation about what this tool does besides sanitizing. which chars are decoded (at least the &amp;nbsp) and which are encoded.

**Comment by mikesamuel** [comment]
I'm intentionally not specifying that.  Clients should not rely on the exact character output because I may change that in response to new threats.

**Comment by tibistibi** [comment]
ah ok so basically user who use this tool should be warned that by upgrading the encoding and decoding could changed without notice.

**Comment by jmanico** [comment]
Those changes would be discussed in release notes.

Again, if you are upset at Mr. Samuels choices, I encourage you to fork 
the project.

Please note that Michael is a volunteer and this is an open source 
project that he has donated to the OWASP foundation. He is also kind 
enough to continue maintaining the project to the best of his ability.

Please be sure to maintain respectful, helpful discourse.

Aloha,
Jim

**Comment by tibistibi** [comment]
jim first I’m not addressing anyone in particular, anyone with knowledge of the project can respond.

second I spend my time on this forum/issue because I think it will improve the product so it could be used in more real life situations. I see some other posters who have problems with the encoding and decoding like myself. 

third there was a question to provide clear and well argued cases, so that's what I’m doing.

off course I can fork the project to change it to whatever I want but that will not improve the community it will just clutter it and probably my implementation will not be as good because off lake of experience and overview being new to the code. 

and finally  if you think I’m in any way not respectful just point me to what sentence let you think that so I can update it. I’m not a native English speaker so it could be that I made some mistakes.

**Comment by jmanico** [comment]
Fair comments and thank you for your support.

--
Jim Manico
@Manicode
(808) 652-3805
