### ISSUE TITLE
Ending Tag Removal Not Emitting Event for HtmlChangeListener

### ISSUE THREAD

**Issue by brutalhonesty** [OWASP/java-html-sanitizer#44]
Hey there,

I wanted to use this sanitization library to help detect issues with HTML input. I noticed that when I have an closing tag in my input with no opening tag, the sanitizer will take care of it but will not emit an event in the HtmlChangeListener.
I think it might be related to this as well:
https://github.com/OWASP/java-html-sanitizer/issues/40

Would greatly appreciate if this closing tag with no opening tag could be emitted as an event to be captured in my implementation of the HtmlChangeListener.

Thank you

**Comment by brutalhonesty** [comment]
What I want to do is run the renderer first then apply the policy. Sanitization is optional for my use case.

Example policy:
Only allow tags <code>p,b,br</code> and no attributes.

Input: "\<p\>Paragraph Text" with no quotes.

The sanitizer is picking this up and making it "\<p\>Paragraph Text\</p\>" and then the renderer is seeing the opening tag and closing tag and thinks all is good. But if I don't want to keep the sanitized input and just find out if the input data was valid, it invalidates my check.

How can I get "\<p\>Paragraph Text" to see an imbalance in the tags and throw an event and also checking for my policy?

This issue also happens with input such as "Paragraph Text\</p\>"

**Comment by mikesamuel** [comment]
> But if I don't want to keep the sanitized input and just find out if the input data was valid, it invalidates my check.

Could you explain in a little more detail what you mean by "valid?"

**Comment by brutalhonesty** [comment]
Valid is whether or not the input passes the whitelist check.

**Comment by mikesamuel** [comment]
Once you know that an input is valid, how would you treat it differently?  It seems to me that "valid" does not imply safe to interpolate into a page.

For example,

```html
<!-- -\0-> <script>alert(1337)</script> -->
```

where `\0` is a NUL character might be interpreted as containing no tags because some parsers (including the one used by this sanitizer) might treat the whole thing as a comment, but if you were to then use that string, other browsers' parsers might drop the NUL and treat the `<script>...</script>` as significant.


Similarly

```html
<!--[if true]> <script>alert(1337)</script> -->
```

arguably only contains a comment, but IE will reliably parse it as containing a script element.


```html
<![CDATA[ <!-- ]]> <script>alert(1337)</script> <!-- -->
```

will reliably execute a script when interpolated into an XHTML document or HTML foreign content context but a parser that expects non-foreign HTML comment sees no tags.


For this sanitizer to do its job, it filters, **and** normalizes to make sure that the output is in a subset of HTML that is consistently interpreted by browsers.  Skipping that last step is asking for trouble.

**Comment by jmanico** [comment]
Because we do "sanitize" it's VERY difficult to accurately (and safely) provide an isValid. Even diff'ing input vs output will not satisfy this need. I labeled this wontfix and am closing the bug. I am sorry this kind of tech cannot satisfy this request, we submit with respect.
