### ISSUE TITLE
Is there support for HTML5 data attributes?

### ISSUE THREAD

**Issue by manish-in-java** [OWASP/java-html-sanitizer#51]
I would like to allow users to provide HTML code such as:

    <a data-target="..." data-action="..." data-profile="...">...</a>

Basically, any number of attributes on a tag (`a` in this example) that begin with `data-`.  Is it possible do this with `HtmlPolicyBuilder` (or otherwise)?

**Comment by jmanico** [comment]
Yes it's possible to create all kinds of HTML 5 policies. If you have specific questions beyond this please email the list, email the lead or open a new issue! :) Aloha!

**Comment by manish-in-java** [comment]
Haven't see any examples of achieving this. There are no tests to cover this either. I want `data-*` attributes to be allowed on all HTML elements. How would this be done through the `HtmlPolicyBuilder`?

**Comment by mikesamuel** [comment]
I got slammed at work, but will work on HTML 5 stuff.

`data-*` attributes will never be supported.

The [HTML 5 spec 3.2.5.9](https://www.w3.org/TR/html5/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes) says

> Custom data attributes are intended to store custom data private to the page or application, for which there are no more appropriate attributes or elements.

> These attributes are not intended for use by software that is independent of the site that uses the attributes.

> ...

> It would be inappropriate, however, for the user to use generic software not associated with that music site to search for tracks of a certain length by looking at this data.

> This is because these attributes are intended for use by the site's own scripts, and **are not a generic extension mechanism for publicly-usable metadata.**


Since the input to the sanitizer is HTML that does not obviously originate from within the same origin as the HTML into which it is included, arbitrary `data-*` attributes should not be allowed.

----

Because of that convention, it's not unreasonable for a JavaScript coder to write something like

```js
var foo = document.querySelectorAll('*[@data-mycompany-spiffyurl]');
for (var i = 0, n = foo.length; i < n; ++i) {
  doSomethingWith(foo[i].getAttribute('data-mycompany-spiffyurl'));
}
```

If sanitized HTML can specify arbitrary `data-*` strings then it is easier for an attacker to get a `javascript:` URL to a browser builtin that treats it as code or a string of JavaScript to `eval(...)`.

You can whitelist specific data attributes in a policy, but policies that blanket allow `data-*` attributes violate 

1. widespread assumptions about how HTML is used, 
2. widespread security practices of preferring white-listing to black-listing,
 
and I have yet to see a use case for it that can't be addressed with a white list or that doesn't involve embedding data in attribute names (see 1).
