### ISSUE TITLE
Special treatment of {{...}} pattern breaking existing application

### ISSUE THREAD

**Issue by manish-in-java** [OWASP/java-html-sanitizer#69]
Issues #55 and #56 deal with the special treatment accorded to the `{{...}}` pattern. This was effected in [4f9a7af](https://github.com/OWASP/java-html-sanitizer/commit/4f9a7af04a906d03ce75561f513cf7b151025193#diff-4685b71e19e2f1de0ad0098cc62d6dbb).

We parse the `{{...}}` pattern on the server-side and replace them with links specific to our application. We do not use the `{{...}}` pattern on the client side. [4f9a7af](https://github.com/OWASP/java-html-sanitizer/commit/4f9a7af04a906d03ce75561f513cf7b151025193#diff-4685b71e19e2f1de0ad0098cc62d6dbb) changes `{{...}}` to `{<!-- -->{...}}`, which has started breaking our server-side code.

At the very least, there should be a configuration option somewhere (may be on the `PolicyBuilder`) that allows us to control when we want `{{...}}` to be changed to `{<!-- -->{...}}`. Doing so without any configurability assumes that the pattern is used only by Mustache (or a client-side templating engine) and breaks other libraries that use similar syntax.

**Comment by mikesamuel** [comment]
Why not just do the replacement prior to sanitizing?

**Comment by mikesamuel** [comment]
It seems like if you're doing this, it would be better to replace `{<!-- --->{...}}` with links because that way you're assured that you're not inserting links into elements as in

```html
<span title="{{...}}">
```

Post-processing HTML by search replace is error prone, so I don't think use cases that involve it are valid reasons for expanding APIs.

You could probably do what you want by using a custom `HtmlStreamEventReceiver` that overrides [`text`](http://static.javadoc.io/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer/20160422.1/org/owasp/html/HtmlStreamEventReceiver.html#text-java.lang.String-) to look for `{{...}}` and delegates others to an `HtmlStreamRenderer`

**Comment by mikesamuel** [comment]
Relase [20160526.1](http://search.maven.org/#artifactdetails%7Ccom.googlecode.owasp-java-html-sanitizer%7Cowasp-java-html-sanitizer%7C20160526.1%7Cjar) adds [`withPostProcessor`](https://github.com/OWASP/java-html-sanitizer/blob/master/src/main/java/org/owasp/html/HtmlPolicyBuilder.java#L464-L478) that should allow you to handle this without doing search/replace on sanitized text.

Mucking with sanitized text is error prone because of things like `{{...}}` that appear inside attributes or that cross element/attribute boundaries.

Instead, with the new version you can do

```java
myPolicyBuilder
    .withPostprocessor(new HtmlStreamEventProcessor() {
      public HtmlStreamEventReceiver wrap(HtmlStreamEventReceiver sink) {
         return new HtmlStreamEventReceiverWrapper(sink) {
           @Override
           public void text(String text) {
             // Look for occurrences of {{...}} in text, split around them, and insert links.
             int textEmitted = 0;
             Matcher m = Pattern.compile("[{][{](.*?)[}][}]", Pattern.DOT_ALL).matcher(text);
             while (textEmitted < text.length()) {
               if (match.find()) {
                 int start = m.start();
                 if (start != textEmitted) {
                   underlying.text(text.substring(textEmitted, start);
                 }
                 textEmitted = m.end();

                 String substitutionHref;
                 String linkText;
                 /* DO something with matcher.group(1) to populate the above */
                 underlying.openTag("a", ImmutableList.of("href", substitutionHref);
                 underlying.text(linkText);
                 underlying.closeTag("a");
               } else {
                 underlying.text(text.substring(textEmitted));
                 textEmitted = text.length;
                 break;
               }
             }
           }
         };
      }  
    });
```

This allows the `HtmlStreamEventRenderer` to preserve token boundaries.
